version: "3.8"
services:
  container_erp_db:
    image: postgres
    container_name: container_erp_db
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Admin@123!
      POSTGRES_DB: erp_dev
    volumes:
      - ./data-db:/var/lib/postgresql/data
  container_erp_pgadmin:
    image: dpage/pgadmin4
    container_name: container_erp_pgadmin
    restart: always
    ports:
      - "8085:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: Admin@123!
    volumes:
      - data-pgadmin:/var/lib/pgadmin

volumes:
  data-db:
  data-pgadmin: